# Generated by Django 3.2.4 on 2021-06-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=300)),
                ('due_date', models.DateTimeField()),
                ('hours_needed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('days_needed', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
