# Generated by Django 3.1.6 on 2021-08-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="days",
            name="user",
        ),
    ]
