# Generated by Django 3.1.6 on 2021-08-13 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduler", "0003_days_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="days",
            name="user",
        ),
        migrations.AddField(
            model_name="taskinfo",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskinfo",
            name="days_needed",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=4
            ),
        ),
    ]
