# Generated by Django 3.1.6 on 2021-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20210813_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='due_date',
            field=models.DateField(),
        ),
    ]
