# Generated by Django 3.1.6 on 2021-08-13 23:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduler", "0005_auto_20210813_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinfo",
            name="created_date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="taskinfo",
            name="gradient",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="taskinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
