# Generated by Django 3.1.6 on 2021-08-13 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20210813_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
