# Generated by Django 3.1.6 on 2021-08-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20210814_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='modified_date',
            field=models.DateField(null=True),
        ),
    ]
