# Generated by Django 3.1.6 on 2021-08-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20210818_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='gradient',
            field=models.CharField(choices=[['+', 'Increasing'], ['-', 'Decreasing'], ['0', 'Roughly same']], default='+', max_length=1),
        ),
    ]
