# Generated by Django 3.1.6 on 2021-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0017_days_extra_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskinfo",
            name="hours_needed",
            field=models.DecimalField(
                decimal_places=2, default=10, max_digits=5
            ),
        ),
    ]
