# Generated by Django 3.1.6 on 2021-09-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_auto_20210905_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
