# Generated by Django 3.1.6 on 2021-10-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_taskinfo_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='test',
            field=models.DateField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='hours_2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
