# Generated by Django 3.1.6 on 2021-10-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_remove_days_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='hours_2',
        ),
    ]
